name: PlatformIO Builds

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build ProtocolAnalyzer
        run: pio run
        working-directory: ./test/ProtocolAnalyzer

      - name: Build ListCapabilities
        run: pio run
        working-directory: ./test/ListCapabilities

      - name: Build VoltageChange
        run: pio run
        working-directory: ./test/VoltageChange
